/* 
 * Aspose.ThreeD Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Aspose.ThreeD.Cloud.SDK.Client;
using Aspose.ThreeD.Cloud.SDK.Model;

namespace Aspose.ThreeD.Cloud.SDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStorageApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get disc usage
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>DiscUsage</returns>
        DiscUsage GetDiscUsage (string storageName = null);

        /// <summary>
        /// Get disc usage
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>ApiResponse of DiscUsage</returns>
        ApiResponse<DiscUsage> GetDiscUsageWithHttpInfo (string storageName = null);
        /// <summary>
        /// Get file versions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File path e.g. &#39;/file.ext&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>FileVersions</returns>
        FileVersions GetFileVersions (string path, string storageName = null);

        /// <summary>
        /// Get file versions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File path e.g. &#39;/file.ext&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>ApiResponse of FileVersions</returns>
        ApiResponse<FileVersions> GetFileVersionsWithHttpInfo (string path, string storageName = null);
        /// <summary>
        /// Check if file or folder exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File or folder path e.g. &#39;/file.ext&#39; or &#39;/folder&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <param name="versionId">File version ID (optional)</param>
        /// <returns>ObjectExist</returns>
        ObjectExist ObjectExists (string path, string storageName = null, string versionId = null);

        /// <summary>
        /// Check if file or folder exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File or folder path e.g. &#39;/file.ext&#39; or &#39;/folder&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <param name="versionId">File version ID (optional)</param>
        /// <returns>ApiResponse of ObjectExist</returns>
        ApiResponse<ObjectExist> ObjectExistsWithHttpInfo (string path, string storageName = null, string versionId = null);
        /// <summary>
        /// Check if storage exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name</param>
        /// <returns>StorageExist</returns>
        StorageExist StorageExists (string storageName);

        /// <summary>
        /// Check if storage exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name</param>
        /// <returns>ApiResponse of StorageExist</returns>
        ApiResponse<StorageExist> StorageExistsWithHttpInfo (string storageName);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get disc usage
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>Task of DiscUsage</returns>
        System.Threading.Tasks.Task<DiscUsage> GetDiscUsageAsync (string storageName = null);

        /// <summary>
        /// Get disc usage
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>Task of ApiResponse (DiscUsage)</returns>
        System.Threading.Tasks.Task<ApiResponse<DiscUsage>> GetDiscUsageAsyncWithHttpInfo (string storageName = null);
        /// <summary>
        /// Get file versions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File path e.g. &#39;/file.ext&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>Task of FileVersions</returns>
        System.Threading.Tasks.Task<FileVersions> GetFileVersionsAsync (string path, string storageName = null);

        /// <summary>
        /// Get file versions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File path e.g. &#39;/file.ext&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>Task of ApiResponse (FileVersions)</returns>
        System.Threading.Tasks.Task<ApiResponse<FileVersions>> GetFileVersionsAsyncWithHttpInfo (string path, string storageName = null);
        /// <summary>
        /// Check if file or folder exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File or folder path e.g. &#39;/file.ext&#39; or &#39;/folder&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <param name="versionId">File version ID (optional)</param>
        /// <returns>Task of ObjectExist</returns>
        System.Threading.Tasks.Task<ObjectExist> ObjectExistsAsync (string path, string storageName = null, string versionId = null);

        /// <summary>
        /// Check if file or folder exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File or folder path e.g. &#39;/file.ext&#39; or &#39;/folder&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <param name="versionId">File version ID (optional)</param>
        /// <returns>Task of ApiResponse (ObjectExist)</returns>
        System.Threading.Tasks.Task<ApiResponse<ObjectExist>> ObjectExistsAsyncWithHttpInfo (string path, string storageName = null, string versionId = null);
        /// <summary>
        /// Check if storage exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name</param>
        /// <returns>Task of StorageExist</returns>
        System.Threading.Tasks.Task<StorageExist> StorageExistsAsync (string storageName);

        /// <summary>
        /// Check if storage exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name</param>
        /// <returns>Task of ApiResponse (StorageExist)</returns>
        System.Threading.Tasks.Task<ApiResponse<StorageExist>> StorageExistsAsyncWithHttpInfo (string storageName);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class StorageApi : IStorageApi
    {
        private Aspose.ThreeD.Cloud.SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StorageApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StorageApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Aspose.ThreeD.Cloud.SDK.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }
		
		/// <summary>
        /// Initializes a new instance of the <see cref="StorageApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StorageApi(String basePath, String accesstoken)
        {
            Dictionary<string, string> headerParameters = new Dictionary<string, string>();
            headerParameters.Add("Authorization", "Bearer " + accesstoken);
            this.Configuration = new Configuration(new ApiClient(basePath),headerParameters);

            ExceptionFactory = Aspose.ThreeD.Cloud.SDK.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StorageApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StorageApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Aspose.ThreeD.Cloud.SDK.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }
		
		/// <summary>
        /// Initializes a new instance of the <see cref="StorageApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StorageApi(String grantType,String appSID,String appKey)
        {
            OAuthApi oauth2 = new OAuthApi("https://api.aspose.cloud");
            var oauth2response = oauth2.OAuthPost(grantType, appSID, appKey);
            Dictionary<string, string> headerParameters = new Dictionary<string, string>();
            headerParameters.Add("Authorization", "Bearer " + oauth2response.AccessToken);
            this.Configuration =  new Configuration(new ApiClient(), headerParameters);
            ExceptionFactory = Aspose.ThreeD.Cloud.SDK.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Aspose.ThreeD.Cloud.SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get disc usage 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>DiscUsage</returns>
        public DiscUsage GetDiscUsage (string storageName = null)
        {
             ApiResponse<DiscUsage> localVarResponse = GetDiscUsageWithHttpInfo(storageName);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get disc usage 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>ApiResponse of DiscUsage</returns>
        public ApiResponse< DiscUsage > GetDiscUsageWithHttpInfo (string storageName = null)
        {

            var localVarPath = "3d/storage/disc";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (storageName != null) localVarQueryParams.Add("storageName", Configuration.ApiClient.ParameterToString(storageName)); // query parameter

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDiscUsage", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DiscUsage>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DiscUsage) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DiscUsage)));
        }

        /// <summary>
        /// Get disc usage 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>Task of DiscUsage</returns>
        public async System.Threading.Tasks.Task<DiscUsage> GetDiscUsageAsync (string storageName = null)
        {
             ApiResponse<DiscUsage> localVarResponse = await GetDiscUsageAsyncWithHttpInfo(storageName);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get disc usage 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>Task of ApiResponse (DiscUsage)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DiscUsage>> GetDiscUsageAsyncWithHttpInfo (string storageName = null)
        {

            var localVarPath = "3d/storage/disc";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (storageName != null) localVarQueryParams.Add("storageName", Configuration.ApiClient.ParameterToString(storageName)); // query parameter

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDiscUsage", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DiscUsage>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DiscUsage) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DiscUsage)));
        }

        /// <summary>
        /// Get file versions 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File path e.g. &#39;/file.ext&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>FileVersions</returns>
        public FileVersions GetFileVersions (string path, string storageName = null)
        {
             ApiResponse<FileVersions> localVarResponse = GetFileVersionsWithHttpInfo(path, storageName);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get file versions 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File path e.g. &#39;/file.ext&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>ApiResponse of FileVersions</returns>
        public ApiResponse< FileVersions > GetFileVersionsWithHttpInfo (string path, string storageName = null)
        {
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling StorageApi->GetFileVersions");

            var localVarPath = "3d/storage/version/{path}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (path != null) localVarPathParams.Add("path", Configuration.ApiClient.ParameterToString(path)); // path parameter
            if (storageName != null) localVarQueryParams.Add("storageName", Configuration.ApiClient.ParameterToString(storageName)); // query parameter

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetFileVersions", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<FileVersions>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (FileVersions) Configuration.ApiClient.Deserialize(localVarResponse, typeof(FileVersions)));
        }

        /// <summary>
        /// Get file versions 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File path e.g. &#39;/file.ext&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>Task of FileVersions</returns>
        public async System.Threading.Tasks.Task<FileVersions> GetFileVersionsAsync (string path, string storageName = null)
        {
             ApiResponse<FileVersions> localVarResponse = await GetFileVersionsAsyncWithHttpInfo(path, storageName);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get file versions 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File path e.g. &#39;/file.ext&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <returns>Task of ApiResponse (FileVersions)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<FileVersions>> GetFileVersionsAsyncWithHttpInfo (string path, string storageName = null)
        {
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling StorageApi->GetFileVersions");

            var localVarPath = "3d/storage/version/{path}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (path != null) localVarPathParams.Add("path", Configuration.ApiClient.ParameterToString(path)); // path parameter
            if (storageName != null) localVarQueryParams.Add("storageName", Configuration.ApiClient.ParameterToString(storageName)); // query parameter

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetFileVersions", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<FileVersions>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (FileVersions) Configuration.ApiClient.Deserialize(localVarResponse, typeof(FileVersions)));
        }

        /// <summary>
        /// Check if file or folder exists 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File or folder path e.g. &#39;/file.ext&#39; or &#39;/folder&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <param name="versionId">File version ID (optional)</param>
        /// <returns>ObjectExist</returns>
        public ObjectExist ObjectExists (string path, string storageName = null, string versionId = null)
        {
             ApiResponse<ObjectExist> localVarResponse = ObjectExistsWithHttpInfo(path, storageName, versionId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Check if file or folder exists 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File or folder path e.g. &#39;/file.ext&#39; or &#39;/folder&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <param name="versionId">File version ID (optional)</param>
        /// <returns>ApiResponse of ObjectExist</returns>
        public ApiResponse< ObjectExist > ObjectExistsWithHttpInfo (string path, string storageName = null, string versionId = null)
        {
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling StorageApi->ObjectExists");

            var localVarPath = "3d/storage/exist/{path}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (path != null) localVarPathParams.Add("path", Configuration.ApiClient.ParameterToString(path)); // path parameter
            if (storageName != null) localVarQueryParams.Add("storageName", Configuration.ApiClient.ParameterToString(storageName)); // query parameter
            if (versionId != null) localVarQueryParams.Add("versionId", Configuration.ApiClient.ParameterToString(versionId)); // query parameter

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ObjectExists", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ObjectExist>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ObjectExist) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ObjectExist)));
        }

        /// <summary>
        /// Check if file or folder exists 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File or folder path e.g. &#39;/file.ext&#39; or &#39;/folder&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <param name="versionId">File version ID (optional)</param>
        /// <returns>Task of ObjectExist</returns>
        public async System.Threading.Tasks.Task<ObjectExist> ObjectExistsAsync (string path, string storageName = null, string versionId = null)
        {
             ApiResponse<ObjectExist> localVarResponse = await ObjectExistsAsyncWithHttpInfo(path, storageName, versionId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Check if file or folder exists 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">File or folder path e.g. &#39;/file.ext&#39; or &#39;/folder&#39;</param>
        /// <param name="storageName">Storage name (optional)</param>
        /// <param name="versionId">File version ID (optional)</param>
        /// <returns>Task of ApiResponse (ObjectExist)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ObjectExist>> ObjectExistsAsyncWithHttpInfo (string path, string storageName = null, string versionId = null)
        {
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling StorageApi->ObjectExists");

            var localVarPath = "3d/storage/exist/{path}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (path != null) localVarPathParams.Add("path", Configuration.ApiClient.ParameterToString(path)); // path parameter
            if (storageName != null) localVarQueryParams.Add("storageName", Configuration.ApiClient.ParameterToString(storageName)); // query parameter
            if (versionId != null) localVarQueryParams.Add("versionId", Configuration.ApiClient.ParameterToString(versionId)); // query parameter

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ObjectExists", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ObjectExist>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ObjectExist) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ObjectExist)));
        }

        /// <summary>
        /// Check if storage exists 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name</param>
        /// <returns>StorageExist</returns>
        public StorageExist StorageExists (string storageName)
        {
             ApiResponse<StorageExist> localVarResponse = StorageExistsWithHttpInfo(storageName);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Check if storage exists 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name</param>
        /// <returns>ApiResponse of StorageExist</returns>
        public ApiResponse< StorageExist > StorageExistsWithHttpInfo (string storageName)
        {
            // verify the required parameter 'storageName' is set
            if (storageName == null)
                throw new ApiException(400, "Missing required parameter 'storageName' when calling StorageApi->StorageExists");

            var localVarPath = "3d/storage/{storageName}/exist";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (storageName != null) localVarPathParams.Add("storageName", Configuration.ApiClient.ParameterToString(storageName)); // path parameter

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StorageExists", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StorageExist>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (StorageExist) Configuration.ApiClient.Deserialize(localVarResponse, typeof(StorageExist)));
        }

        /// <summary>
        /// Check if storage exists 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name</param>
        /// <returns>Task of StorageExist</returns>
        public async System.Threading.Tasks.Task<StorageExist> StorageExistsAsync (string storageName)
        {
             ApiResponse<StorageExist> localVarResponse = await StorageExistsAsyncWithHttpInfo(storageName);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Check if storage exists 
        /// </summary>
        /// <exception cref="Aspose.ThreeD.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storageName">Storage name</param>
        /// <returns>Task of ApiResponse (StorageExist)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<StorageExist>> StorageExistsAsyncWithHttpInfo (string storageName)
        {
            // verify the required parameter 'storageName' is set
            if (storageName == null)
                throw new ApiException(400, "Missing required parameter 'storageName' when calling StorageApi->StorageExists");

            var localVarPath = "3d/storage/{storageName}/exist";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (storageName != null) localVarPathParams.Add("storageName", Configuration.ApiClient.ParameterToString(storageName)); // path parameter

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StorageExists", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StorageExist>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (StorageExist) Configuration.ApiClient.Deserialize(localVarResponse, typeof(StorageExist)));
        }

    }
}
